extends: '@commitlint/config-conventional'

rules:
  type-enum:
    - 2
    - always
    - ['feat', 'fix', 'chore', 'docs', 'style', 'refactor', 'perf', 'test']
  header-max-length:
    - 2
    - always
    - 100
  body-max-line-length:
    - 2
    - always
    - 100
  footer-max-line-length:
    - 2
    - always
    - 100
