name: RuboCop Linter

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'
      - '!master'

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1

    - name: Install dependencies
      run: bundle install

    - name: Run RuboCop
      run: rubocop .

    - name: Fail if RuboCop errors
      run: |
        set -e
        bundle exec rubocop
        result=$?
        if [ $result -ne 0 ]; then
          echo "::error::RuboCop errors found. Please fix them before merging."
          exit 1
        fi
